# Generated by Django 5.2.17 on 2026-09-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
