# Generated by Django 5.2.17 on 2026-09-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_perfume_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_chords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('type', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_chords', models.ManyToManyField(blank=True, to='perfumes.main_chords')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='main_chords',
            field=models.ManyToManyField(blank=True, to='perfumes.main_chords'),
        ),
    ]
