# Generated by Django 5.2.17 on 2026-10-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_remove_container_image_url_remove_perfume_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='catalog',
            field=models.CharField(choices=[('caballero', 'Caballero'), ('dama', 'Dama'), ('arabe', 'Arabe')], default='caballero', max_length=20),
        ),
    ]
